url: https://Abdullah-Ghani.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: RCT
email: abdullah.ghani@rutgers.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Shantenu Jha
  pic: 1
  position: Associate Professor
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/shantenu-jha-5625153/
    - title: github
      url: https://github.com/shantenujha


- name: Andre Merkzy
  pic: 2
  position: Lead Developer
  social:
    - title: linkedin
      url: #
    - title: github
      url: https://github.com/andre-merzky

- name: Abdullah Ghani
  pic: 3
  position: Student Researcher
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/abdullah-ghani-4a3849141/
    - title: github
      url: https://github.com/Abdullah-Ghani

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LabRadical
  - title: github
    url: https://github.com/radical-cybertools

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
